service: express-app

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline